### ISSUE TITLE
Integration in bioptim may be wrong.

### ISSUE THREAD

**Issue by Ipuch** [Kev1CO/optistim#7]
Hey,

f1(x,u) = f(x,u,t1) may be wrongly used for time integration by OdeSolvers has we call multiple time the functions.

**Comment by Ipuch** [comment]
see 
[#701](https://github.com/pyomeca/bioptim/issues/701)
[#708](https://github.com/pyomeca/bioptim/pull/718)

**Comment by Kev1CO** [comment]
Closed with PR #18
